version: "3.4"
services:
  db:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - dbdata:/pgdata
    env_file: db/env
  app:
    container_name: project
    environment:
      - SCENARIO local
    build: 
      context : webapp/
      dockerfile: Dockerfile
      target: local
      args: 
       - SCENARIO=local
    command: gunicorn webapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./webapp:/webapp
      - ./webapp/static:/webapp/static  # <-- bind the static volume
      - ./webapp/media:/webapp/media  # <-- bind the media volume
    healthcheck:
      test: curl --fail http://localhost:8000 || exit
    depends_on: 
      - db 
    links:
      - cache
  cache:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  web:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./serv/:/etc/nginx/conf.d
      - ./webapp/static:/webapp/static  # <-- bind the static volume
      - ./webapp/media:/webapp/media  # <-- bind the media volume
    ports:
      - "80:80"
      - "443:443"
    links:
      - app:app
    depends_on:
      - app
volumes:
  dbdata:
  webapp:
  static_volume:
  media_volume: